### ISSUE TITLE
SSR Support?

### ISSUE THREAD

**Issue by sangelxyz** [feral-dot-io/leptos-chartistry#27]
Hi, is it possible to use chartistry using Leptos SSR. Is there any examples available ?

Thank you

**Comment by feral-dot-io** [comment]
Yes it will work with Leptos SSR without problem and I've not seen any issues come up since #4. There isn't an example of this because there isn't really anything to demo.

I'll close this issue but please reopen if it's not the case.

**Comment by sangelxyz** [comment]
Hi,  it seems to compile fine then i get the following when going to a route directly or refreshing the route. If a link is followed it works fine.

```
thread '<unnamed>' panicked at /home/sangel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-0.2.92/src/lib.rs:1017:1:
function not implemented on non-wasm32 targets
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind

```

**Comment by feral-dot-io** [comment]
Please share an example of your `<Chart ...>` that triggers the error and I'll take a look.

**Comment by feral-dot-io** [comment]
I've pulled together a full SSR example here: https://github.com/feral-dot-io/leptos-chartistry/tree/master/examples/ssr This is all a bit convoluted because you need to pull in leptos-use as a dependency and then toggle its own ssr feature.

I've added this example as a CI build test and the 0.2 / Leptos-0.7 branch now has an SSR feature flag which makes SSR usage sane. So I'll close this issue as done -- thanks for bringing this to my attention.
