### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by VincentBerthier** [feral-dot-io/leptos-chartistry#4]
When using Charistry in SSR mode, I get the following messages (multiple times at once in fact…):
![image](https://github.com/feral-dot-io/leptos-chartistry/assets/34085617/23ec78c4-1ea2-4a74-9600-c58f58bac7c9)

I’ve created a small repro example: https://github.com/VincentBerthier/leptos-repro/tree/charistry
Note that the plot is created correctly: 
![image](https://github.com/feral-dot-io/leptos-chartistry/assets/34085617/835fcc3b-86ea-46a0-a13a-2744ef29f8e8)

**Comment by feral-dot-io** [comment]
Thanks for the repro example. I was able to reproduce the problem easily enough. The fix was simple -- remove the csr feature set on the leptos dependency. Once removed the errors disappeared and things worked normally. This should never have been set on the library crate so I'll file this under glaring omission!
